unit TestuUnitTime;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit
  being tested.

}

interface

uses
  TestFramework, uUnitTime, uUnit;

type
  // Test methods for class THour

  TestTHour = class(TTestCase)
  strict private
    FHour: THour;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestGetRatio;
  end;
  // Test methods for class TDay

  TestTDay = class(TTestCase)
  strict private
    FDay: TDay;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestGetRatio;
  end;

implementation


procedure TestTHour.SetUp;
begin
  FHour := THour.Create;
end;

procedure TestTHour.TearDown;
begin
  FHour.Free;
  FHour := nil;
end;

procedure TestTHour.TestGetRatio;
var
  ReturnValue: Double;
begin
  ReturnValue := FHour.GetRatio;
  CheckEquals(3600, ReturnValue, 'Некорректно установлен параметр для ед. изм. '+FHour.Name+'!');
end;

procedure TestTDay.SetUp;
begin
  FDay := TDay.Create;
end;

procedure TestTDay.TearDown;
begin
  FDay.Free;
  FDay := nil;
end;

procedure TestTDay.TestGetRatio;
var
  ReturnValue: Double;
begin
  ReturnValue := FDay.GetRatio;
  CheckEquals(86400, ReturnValue, 'Некорректно установлен параметр для ед. изм. ' + FDay.Name + '!');
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTHour.Suite);
  RegisterTest(TestTDay.Suite);
end.

