unit TestfmMainApp;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, Vcl.Mask, Vcl.Dialogs, Winapi.Windows, Vcl.StdCtrls, System.SysUtils,
  Vcl.ExtCtrls, Vcl.Graphics, System.Variants, FormMainApp, Winapi.Messages, UnitOfMeasure,
  System.Generics.Collections, Vcl.Controls, Vcl.Forms, ConverterUnit, System.Classes;

type
  // Test methods for class TfmMainApp

  TestTfmMainApp = class(TTestCase)
  strict private
    FfmMainApp: T;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TesteditChange;
  end;

implementation

procedure TestTfmMainApp.SetUp;
begin
  FfmMainApp := TfmMainApp.Create(nil);
end;

procedure TestTfmMainApp.TearDown;
begin
  FfmMainApp.Free;
  FfmMainApp := nil;
end;

procedure TestTfmMainApp.TesteditChange;
var
  Sender: TObject;
  I: integer;
begin
  while True do
  begin
  FfmMainApp.
  FfmMainApp.edFrom.Text := Random(100).ToString;
  ShowMessage(FfmMainApp.edTo.Text);
  // TODO: Setup method call parameters
 // FfmMainApp.editChange(Sender);
  end;
  // TODO: Validate method results
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTfmMainApp.Suite);
end.

